### ISSUE TITLE
How do you generate a authRequestID ? 

### ISSUE THREAD

**Issue by diogosantos-empty** [quochuydev/zitadel-login-ui#3]
Hi!

not really an issue, out just wondering how your generating a authRequestID to be able to login. most of your Code your getting it from the request params, but i dont understand how you get it. could you tell me? 

thanks for your time and good work.

**Comment by quochuydev** [comment]
Add header `x-zitadel-login-client: <serviceUserId>` when requesting to `/authorize`
about `serviceUserId`, you could check the README.md file

ref:
https://github.com/quochuydev/zitadel-login-ui/blob/main/services/backend/oidc.service.ts#L17
https://zitadel.com/docs/guides/integrate/login-ui/oidc-standard#authorize-request

**Comment by diogosantos-empty** [comment]
Hi! Thanks for the quick reply.

i have tried to Add the ```x-zitadel-login-client``` bug that results in :
```json
{
    "code": 12,
    "message": "Method Not Allowed"
}
```

checking the logs, i found this : ``` zitadel-zitadel-1   | ERROR: Failed to extract ServerMetadata from context```

any ideia? 

Thanks

**Comment by quochuydev** [comment]
`/authorize` is get method, are you correct?

**Comment by diogosantos-empty** [comment]
Yee


im sending a GET to ```http://localhost:8080/oauth/v2/authorize?client_id=281564525134675971&redirect_uri=http%3A%2F%2Flocalhost%3A5173%2Fcallback&response_type=code&scope=openid%20email%20profile&code_challenge=9az09PjcfuENS7oDK7jUd2xAWRb-B3N7Sr3kDoWECOY&code_challenge_method=S256```

Zitadel is running on localhost:8080


As you can ser, doing the request without the ```x-zitadel-login-client``` gives me a html page. 

<img width="1429" alt="image" src="https://github.com/user-attachments/assets/9ac02c43-f959-43d8-a0ff-47f014a6184f">

Bug running with the ```x-zitadel-login-client``` gives back the error I mentioned before
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/100522b4-a8b3-4be5-af56-28d0a9339bc4">


any ideia?

**Comment by quochuydev** [comment]
I tested the same as you, and It does not work with Postman, it is correct with `curl` 

```curl
curl "http://localhost:8080/oauth/v2/authorize?client_id=281367778185773059&redirect_uri=http%3A%2F%2Flocalhost%3A5173%2Fcallback&response_type=code&scope=openid%20email%20profile&code_challenge=9az09PjcfuENS7oDK7jUd2xAWRb-B3N7Sr3kDoWECOY&code_challenge_method=S256"
```

```html
<a href="/ui/login/login?authRequestID=282533276281733123">Found</a>.
```

```curl
curl "http://localhost:8080/oauth/v2/authorize?client_id=281367778185773059&redirect_uri=http%3A%2F%2Flocalhost%3A5173%2Fcallback&response_type=code&scope=openid%20email%20profile&code_challenge=9az09PjcfuENS7oDK7jUd2xAWRb-B3N7Sr3kDoWECOY&code_challenge_method=S256" \
-H "x-zitadel-login-client: 282533236754612227"
```

```html
<a href="/login?authRequest=V2_282533280996130819">Found</a>.
```

I haven't used Postman for a long time 😀

**Comment by diogosantos-empty** [comment]
Your right!

and the weird part is that i also tried curl using postman generated command that looks like this : 
```curl --location 'http://localhost:8080/oauth/v2/authorize?client_id=281564525134675971&redirect_uri=http%3A%2F%2Flocalhost%3A5173%2Fcallback&response_type=code&scope=openid%20email%20profile&code_challenge=9az09PjcfuENS7oDK7jUd2xAWRb-B3N7Sr3kDoWECOY&code_challenge_method=S256' --header 'x-zitadel-login-client: 282141924515643395'```

it has a ```--location``` and that was also causing the ```{
    "code": 12,
    "message": "Method Not Allowed"
}```

i barely use postman and i guess this is another reason not to 😆

thanks for all the help and have a good day 😀
